
import math
from .models import Project, Track, Keyframe, CurveType

class GLSLExporter:
    def __init__(self, project: Project):
        self.project = project
        
    def export(self, range_start=None, range_end=None) -> str:
        code = []
        
        # 1. Header & Defines
        code.append("#ifndef LASER_SHOW_GLSL")
        code.append("#define LASER_SHOW_GLSL")
        code.append("// Generated by Laser Show Designer")
        code.append(f"// BPM: {self.project.bpm}")
        code.append(f"// Length: {self.project.total_measures} measures")
        if range_start is not None and range_end is not None:
             code.append(f"// Range: Measure {range_start} to {range_end}")
        code.append("")
        
        # 2. Math Helpers (Curves)
        code.append(self._generate_math_helpers())
        
        # 3. Track Functions
        self.param_map = {
            "pos.x": "PosX", "pos.y": "PosY", "pos.z": "PosZ",
            "dir.x": "DirX", "dir.y": "DirY", "dir.z": "DirZ",
            "color.r": "ColorR", "color.g": "ColorG", "color.b": "ColorB",
            "brightness": "Brightness",
            "thickness": "Thickness",
            "divergence": "Divergence",
            "attenuation": "Attenuation",
            "params.x": "ParamX", "params.y": "ParamY", "params.z": "ParamZ", "params.w": "ParamW",
            "localUp.x": "LocalUpX", "localUp.y": "LocalUpY", "localUp.z": "LocalUpZ",
            "type": "Type",
            "is_master": "IsMaster"
        }
        
        # Add offset params to map
        base_keys = list(self.param_map.keys())
        for k in base_keys:
            v = self.param_map[k]
            self.param_map[f"offset_{k}"] = f"Offset{v}"
            self.param_map[f"offset_mode_{k}"] = f"Mode{v}"
        
        track_funcs = []
        laser_tracks = {}
        for i, laser in enumerate(self.project.lasers):
            laser_tracks[laser.name] = []
            
        for track in self.project.tracks:
            if track.target_laser not in laser_tracks:
                continue
                
            laser_idx = -1
            for idx, l in enumerate(self.project.lasers):
                if l.name == track.target_laser:
                    laser_idx = idx
                    break
            
            if laser_idx >= 0:
                func_code = self._generate_track_func(laser_idx, track, range_start, range_end)
                if func_code:
                    track_funcs.append(func_code)
                    laser_tracks[track.target_laser].append(track)
                    
        code.append("\n".join(track_funcs))
        
        # 4. Update Function
        code.append(self._generate_update_function(laser_tracks))
        
        # 5. Draw Function
        code.append(self._generate_draw_function())
        
        code.append("#endif // LASER_SHOW_GLSL")
        
        return "\n".join(code)
    
    def _generate_draw_function(self) -> str:
        laser_count = len(self.project.lasers)
        if laser_count == 0:
            return """
vec3 drawLaserShow(vec3 cameraPos, vec3 viewDir, float maxViewDist, float time, vec3 targetPosUnused) {
    return vec3(0.0);
}
"""
        
        return f"""
vec3 drawLaserShow(vec3 cameraPos, vec3 viewDir, float maxViewDist, float time, vec3 targetPosUnused) {{
    // Music Configuration
    const float BPM = {self.project.bpm:.1f};
    const float BEATS_PER_BAR = {self.project.beats_per_bar:.1f};
    const float SECONDS_PER_BEAT = 60.0 / BPM;
    
    // Global Time (seconds)
    // Map sunAngle 0.55 -> 0.0s. 1.0 sunAngle = 1200s.
    // Wrap around handled by user logic or simple offset here.
    // Assuming linear day:
    float sunAngle = time;
    float relSun = sunAngle - 0.55;
    // Simple wrap for day/night cycle if needed, but assuming simple play:
    float showTime = relSun * 1200.0;
    
    // Safety check if user passes raw seconds instead of sunAngle
    if (time > 2.0) showTime = time; 

    float totalBeats = showTime / SECONDS_PER_BEAT;
    
    // Define Lasers
    const int MAX_LASERS = {laser_count};
    Laser lasers[MAX_LASERS];
    
    // Update Animation
    updateLasers(totalBeats, lasers);
    
    // Accumulate Color
    vec3 totalColor = vec3(0.0);
    
    for(int i=0; i<MAX_LASERS; i++) {{
        totalColor += getLaserContribution(lasers[i], cameraPos, viewDir, maxViewDist, showTime);
    }}
    
    return totalColor;
}}
"""
    
    def _generate_math_helpers(self) -> str:
        return """
// --- Curve Interpolation ---
float interpolate_curve(float v1, float v2, float t, int type, float tension) {
    float delta = v2 - v1;
    
    // HOLD
    if (type == 1) return v1;
    
    // SMOOTH (SmoothStep)
    if (type == 0) {
        float val_smooth = t * t * (3.0 - 2.0 * t);
        float val_linear = t;
        float factor = clamp(abs(tension), 0.0, 1.0);
        float t_mixed = mix(val_smooth, val_linear, factor);
        return v1 + delta * t_mixed;
    }
    
    // SINGLE_CURVE
    if (type == 2) {
        if (abs(tension) < 0.001) return v1 + delta * t;
        float exponent = 1.0;
        if (tension > 0.0) exponent = 1.0 + 5.0 * tension;
        else exponent = 1.0 / (1.0 + 5.0 * abs(tension));
        return v1 + delta * pow(t, exponent);
    }
    
    // STAIRS
    if (type == 3) {
        if (abs(tension) < 0.01) return v1 + delta * t;
        float steps = max(1.0, round(abs(tension) * 100.0));
        float t_mapped = floor(t * steps) / steps;
        return v1 + delta * t_mapped;
    }
    
    // SMOOTH_STAIRS
    if (type == 4) {
        if (abs(tension) < 0.01) return v1 + delta * t;
        float steps = max(1.0, round(abs(tension) * 100.0));
        float t_scaled = t * steps;
        float step_idx = floor(t_scaled);
        float step_t = t_scaled - step_idx;
        float step_t_smooth = step_t * step_t * (3.0 - 2.0 * step_t);
        float t_mapped = (step_idx + step_t_smooth) / steps;
        return v1 + delta * t_mapped;
    }
    
    // PULSE
    if (type == 5) {
        if (abs(tension) < 0.01) return v1 + delta * t;
        float count = max(1.0, round(abs(tension) * 100.0));
        float cycle = t * count;
        float phase = cycle - floor(cycle);
        float raw_wave = sin(phase * 6.283185);
        float w = clamp(raw_wave * 10.0, -1.0, 1.0); // Hard clip
        w = (w + 1.0) * 0.5;
        if (tension < 0.0) w = 1.0 - w;
        return v1 + delta * w;
    }
    
    // WAVE
    if (type == 6) {
        if (abs(tension) < 0.01) return v1 + delta * t;
        float count = max(1.0, round(abs(tension) * 100.0));
        float cycle = t * count;
        float phase = cycle - floor(cycle);
        float t_mapped = 0.0;
        if (tension > 0.0) { // Triangle
             t_mapped = 1.0 - 2.0 * abs(phase - 0.5);
        } else { // Sine
             t_mapped = (1.0 - cos(phase * 6.283185)) * 0.5;
        }
        return v1 + delta * t_mapped;
    }

    return v1 + delta * t;
}
"""

    def _generate_track_func(self, laser_idx: int, track: Track, range_start=None, range_end=None) -> str:
        safe_param = self.param_map.get(track.target_param, "Unknown")
        func_name = f"get_L{laser_idx}_{safe_param}"
        
        count = len(track.keyframes)
        if count == 0: return ""
        
        # Sort keyframes just in case
        sorted_kfs = sorted(track.keyframes, key=lambda k: k.time)
        
        # Filter based on range
        if range_start is not None and range_end is not None:
            beats_per_bar = self.project.beats_per_bar
            t_min = (range_start - 1) * beats_per_bar
            t_max = range_end * beats_per_bar
            
            # Find relevant keyframes
            # We need:
            # 1. The last KF <= t_min (to establish state at start of range)
            # 2. All KFs > t_min and < t_max
            # 3. The first KF >= t_max (to establish interpolation out of range)
            
            start_idx = -1
            end_idx = -1
            
            # Find last KF <= t_min
            for i, kf in enumerate(sorted_kfs):
                if kf.time <= t_min:
                    start_idx = i
                else:
                    break
            
            # If no KF before t_min, start from 0? 
            # If start_idx is -1, it means all KFs are > t_min. So we take all starting from 0.
            # If start_idx is valid, we take that one.
            
            # Find first KF >= t_max
            for i in range(len(sorted_kfs) - 1, -1, -1):
                if sorted_kfs[i].time >= t_max:
                    end_idx = i
                else:
                    break
            
            # If end_idx is -1, it means all KFs are < t_max. Take all up to end.
            
            slice_start = 0 if start_idx == -1 else start_idx
            slice_end = len(sorted_kfs) if end_idx == -1 else (end_idx + 1)
            
            relevant_kfs = sorted_kfs[slice_start:slice_end]
            
            # If relevant_kfs is empty (e.g. range is in a gap), we still need the value
            if not relevant_kfs:
                 # Find the state at t_min
                 # Reuse interpolation logic or just find nearest previous
                 last_val = 0.0
                 for kf in sorted_kfs:
                     if kf.time <= t_min: last_val = kf.value
                     else: break
                 # Create a dummy constant track? 
                 # Or just return constant code
                 return f"""
float {func_name}(float t) {{
    return {last_val:.4f};
}}
"""
            
            use_kfs = relevant_kfs
        else:
            use_kfs = sorted_kfs
            
        count = len(use_kfs)
        if count == 0: return "" # Should be handled above
        
        times = []
        values = []
        types = []
        tensions = []
        
        # CurveType Mapping
        ctype_map = {
            CurveType.SMOOTH: 0, CurveType.HOLD: 1, CurveType.SINGLE_CURVE: 2,
            CurveType.STAIRS: 3, CurveType.SMOOTH_STAIRS: 4, CurveType.PULSE: 5,
            CurveType.WAVE: 6
        }
        
        for kf in use_kfs:
            times.append(f"{kf.time:.4f}")
            values.append(f"{kf.value:.4f}")
            types.append(f"{ctype_map.get(kf.curve_type, 0)}")
            tensions.append(f"{kf.tension:.4f}")
            
        lines = []
        lines.append(f"float {func_name}(float t) {{")
        lines.append(f"    if (t <= {times[0]}) return {values[0]};")
        lines.append(f"    if (t >= {times[-1]}) return {values[-1]};")
        
        for i in range(count - 1):
            t0_str = times[i]
            t1_str = times[i+1]
            
            # Check duration
            try:
                dt = float(t1_str) - float(t0_str)
                if dt <= 0.0001: continue
            except:
                continue
                
            lines.append(f"    if (t < {t1_str}) {{")
            lines.append(f"        return interpolate_curve({values[i]}, {values[i+1]}, (t - {t0_str}) / ({t1_str} - {t0_str}), {types[i]}, {tensions[i]});")
            lines.append("    }")
            
        lines.append(f"    return {values[-1]};")
        lines.append("}")
        
        return "\n".join(lines)

    def _generate_update_function(self, laser_tracks) -> str:
        lines = []
        lines.append(f"void updateLasers(float beat, inout Laser lasers[{len(self.project.lasers)}]) {{")
        
        # Helper map for name lookup
        name_to_idx = {l.name: i for i, l in enumerate(self.project.lasers)}
        
        # 1. Initialize all lasers (Base + Tracks)
        for i, laser in enumerate(self.project.lasers):
            lines.append(f"    // Laser {i}: {laser.name}")
            
            # Static Defaults
            p = laser.params
            lines.append(f"    lasers[{i}].pos = vec3({p[0]:.2f}, {p[1]:.2f}, {p[2]:.2f});")
            lines.append(f"    lasers[{i}].dir = vec3({p[3]:.2f}, {p[4]:.2f}, {p[5]:.2f});")
            lines.append(f"    lasers[{i}].color = vec3({p[6]:.3f}, {p[7]:.3f}, {p[8]:.3f});")
            lines.append(f"    lasers[{i}].brightness = {p[9]:.3f};")
            lines.append(f"    lasers[{i}].thickness = {p[10]:.3f};")
            lines.append(f"    lasers[{i}].divergence = {p[11]:.3f};")
            lines.append(f"    lasers[{i}].attenuation = {p[12]:.3f};")
            lines.append(f"    lasers[{i}].params = vec4({p[13]:.3f}, {p[14]:.3f}, {p[15]:.3f}, {p[16]:.3f});")
            lines.append(f"    lasers[{i}].localUp = vec3({p[17]:.2f}, {p[18]:.2f}, {p[19]:.2f});")
            lines.append(f"    lasers[{i}].type = {laser.type};")
            lines.append(f"    lasers[{i}].maxDist = 2000.0;")
            lines.append(f"    lasers[{i}].transparency = 1.0;")
            
            # Apply Tracks
            tracks = laser_tracks.get(laser.name, [])
            for track in tracks:
                if not track.keyframes: continue
                
                # Skip offset tracks here (handled in Master/Slave section)
                if track.target_param.startswith("offset_"): continue
                
                safe_param = self.param_map.get(track.target_param, "Unknown")
                func_name = f"get_L{i}_{safe_param}"
                
                # Assign to struct field
                target = f"lasers[{i}].{track.target_param}"
                
                # Handle vectors manually
                if track.target_param.startswith("pos."): target = f"lasers[{i}].pos.{track.target_param.split('.')[1]}"
                elif track.target_param.startswith("dir."): target = f"lasers[{i}].dir.{track.target_param.split('.')[1]}"
                elif track.target_param.startswith("color."): 
                    target = f"lasers[{i}].color.{track.target_param.split('.')[1]}"
                    lines.append(f"    {target} = {func_name}(beat) / 255.0;")
                    continue
                    
                elif track.target_param.startswith("params."): target = f"lasers[{i}].params.{track.target_param.split('.')[1]}"
                elif track.target_param.startswith("localUp."): target = f"lasers[{i}].localUp.{track.target_param.split('.')[1]}"
                
                elif track.target_param == "divergence":
                    # Degrees to Radians
                    lines.append(f"    lasers[{i}].divergence = radians({func_name}(beat));")
                    continue
                    
                elif track.target_param == "type":
                    lines.append(f"    lasers[{i}].type = int({func_name}(beat));")
                    continue
                
                lines.append(f"    {target} = {func_name}(beat);")
                
        lines.append("")
        lines.append("    // Apply Master/Slave Logic")
        
        # 2. Apply Master/Slave Logic
        for i, laser in enumerate(self.project.lasers):
            if not laser.is_master or not laser.subordinate_ids:
                continue
                
            lines.append(f"    // Master: {laser.name} (ID {i})")
            
            prefix = f"L{i}_"
            
            # Check is_master track
            is_master_track = False
            for t in laser_tracks.get(laser.name, []):
                if t.target_param == "is_master":
                    is_master_track = True
                    break
            
            if is_master_track:
                lines.append(f"    float {prefix}is_master = get_L{i}_IsMaster(beat);")
            else:
                lines.append(f"    float {prefix}is_master = 1.0;")
            
            # Prepare Offset Variables
            op = laser.offset_params
            omp = laser.offset_mode_params
            
            # Helper to generate variable and track
            def gen_offset_var(param_name, idx_range, is_vec=False, vec_type="vec3", is_mode=False):
                mode_str = "_mode" if is_mode else ""
                var_name = f"{prefix}off{mode_str}_{param_name}"
                src_arr = omp if is_mode else op
                
                if is_vec:
                    vals = [src_arr[idx] for idx in idx_range]
                    val_str = ", ".join([f"{v:.3f}" for v in vals])
                    lines.append(f"    {vec_type} {var_name} = {vec_type}({val_str});")
                    
                    # Apply Tracks
                    comps = ["x", "y", "z", "w"][:len(idx_range)]
                    for comp in comps:
                        track_name = f"offset{mode_str}_{param_name}.{comp}"
                        for t in laser_tracks.get(laser.name, []):
                            if t.target_param == track_name:
                                func_name = f"get_L{i}_{self.param_map[track_name]}"
                                divisor = "/ 255.0" if (param_name == "color" and not is_mode) else ""
                                lines.append(f"    {var_name}.{comp} = {func_name}(beat){divisor};")
                else:
                    # Scalar
                    val = src_arr[idx_range[0]]
                    if param_name == "divergence" and not is_mode:
                        lines.append(f"    float {var_name} = radians({val:.3f});")
                    else:
                        lines.append(f"    float {var_name} = {val:.3f};")
                        
                    track_name = f"offset{mode_str}_{param_name}"
                    for t in laser_tracks.get(laser.name, []):
                        if t.target_param == track_name:
                            func_name = f"get_L{i}_{self.param_map[track_name]}"
                            if param_name == "divergence" and not is_mode:
                                lines.append(f"    {var_name} = radians({func_name}(beat));")
                            else:
                                lines.append(f"    {var_name} = {func_name}(beat);")

            # Generate Offsets and Modes
            gen_offset_var("pos", [0, 1, 2], True, "vec3", False)
            gen_offset_var("pos", [0, 1, 2], True, "vec3", True)
            
            gen_offset_var("dir", [3, 4, 5], True, "vec3", False)
            gen_offset_var("dir", [3, 4, 5], True, "vec3", True)
            
            gen_offset_var("color", [6, 7, 8], True, "vec3", False)
            gen_offset_var("color", [6, 7, 8], True, "vec3", True)
            
            gen_offset_var("brightness", [9], False, "", False)
            gen_offset_var("brightness", [9], False, "", True)
            
            gen_offset_var("thickness", [10], False, "", False)
            gen_offset_var("thickness", [10], False, "", True)
            
            gen_offset_var("divergence", [11], False, "", False)
            gen_offset_var("divergence", [11], False, "", True)
            
            gen_offset_var("attenuation", [12], False, "", False)
            gen_offset_var("attenuation", [12], False, "", True)
            
            gen_offset_var("params", [13, 14, 15, 16], True, "vec4", False)
            gen_offset_var("params", [13, 14, 15, 16], True, "vec4", True)
            
            gen_offset_var("localUp", [17, 18, 19], True, "vec3", False)
            gen_offset_var("localUp", [17, 18, 19], True, "vec3", True)
            
            # Apply to Subordinates
            for sub_order_idx, sub_name in enumerate(laser.subordinate_ids):
                if sub_name not in name_to_idx: continue
                sub_idx = name_to_idx[sub_name]
                
                # Multiplier for offset based on order
                mult = float(sub_order_idx + 1)
                
                # Formula: mix(sub, mix(sub, master, mode) + offset * mult, is_master)
                # This matches simulator:
                # If is_master=1:
                #    If mode=0: sub + offset * mult
                #    If mode=1: master + offset * mult
                # If is_master=0: sub
                
                lines.append(f"    lasers[{sub_idx}].pos = mix(lasers[{sub_idx}].pos, mix(lasers[{sub_idx}].pos, lasers[{i}].pos, {prefix}off_mode_pos) + {prefix}off_pos * {mult}, {prefix}is_master);")
                lines.append(f"    lasers[{sub_idx}].dir = mix(lasers[{sub_idx}].dir, mix(lasers[{sub_idx}].dir, lasers[{i}].dir, {prefix}off_mode_dir) + {prefix}off_dir * {mult}, {prefix}is_master);")
                lines.append(f"    lasers[{sub_idx}].color = mix(lasers[{sub_idx}].color, mix(lasers[{sub_idx}].color, lasers[{i}].color, {prefix}off_mode_color) + {prefix}off_color * {mult}, {prefix}is_master);")
                
                lines.append(f"    lasers[{sub_idx}].brightness = mix(lasers[{sub_idx}].brightness, mix(lasers[{sub_idx}].brightness, lasers[{i}].brightness, {prefix}off_mode_brightness) + {prefix}off_brightness * {mult}, {prefix}is_master);")
                lines.append(f"    lasers[{sub_idx}].thickness = mix(lasers[{sub_idx}].thickness, mix(lasers[{sub_idx}].thickness, lasers[{i}].thickness, {prefix}off_mode_thickness) + {prefix}off_thickness * {mult}, {prefix}is_master);")
                lines.append(f"    lasers[{sub_idx}].divergence = mix(lasers[{sub_idx}].divergence, mix(lasers[{sub_idx}].divergence, lasers[{i}].divergence, {prefix}off_mode_divergence) + {prefix}off_divergence * {mult}, {prefix}is_master);")
                lines.append(f"    lasers[{sub_idx}].attenuation = mix(lasers[{sub_idx}].attenuation, mix(lasers[{sub_idx}].attenuation, lasers[{i}].attenuation, {prefix}off_mode_attenuation) + {prefix}off_attenuation * {mult}, {prefix}is_master);")
                
                lines.append(f"    lasers[{sub_idx}].params = mix(lasers[{sub_idx}].params, mix(lasers[{sub_idx}].params, lasers[{i}].params, {prefix}off_mode_params) + {prefix}off_params * {mult}, {prefix}is_master);")
                lines.append(f"    lasers[{sub_idx}].localUp = mix(lasers[{sub_idx}].localUp, mix(lasers[{sub_idx}].localUp, lasers[{i}].localUp, {prefix}off_mode_localUp) + {prefix}off_localUp * {mult}, {prefix}is_master);")
                
        lines.append("}")
        return "\n".join(lines)
        
    def _generate_entry_point(self) -> str:
        # Removed as per new requirement to use laser_show.glsl template
        return ""
